---
vps_vpn_hostname: vpn.afneville.com

data_volume_device: /dev/nvme1n1
data_volume_mount: /srv

vps_admin_ssh_users:
  - ubuntu

caddy_acme_email: contact@afneville.com

headscale_version: 0.28.0
headscale_user: alex
headscale_listen_addr: 127.0.0.1:8080
headscale_stun_listen_addr: 0.0.0.0:3478
headscale_derp_ipv4: ""
headscale_server_hostname: vpn.afneville.com
headscale_dns_base_domain: mesh.afneville.com

tailscale_client_hostname: server-1
tailscale_client_tags:
  - tag:server

syncthing_shared_dir: /srv/syncthing/sync
