#! /bin/sh

bspc rule -r *:*
killall sxhkd
killall -q polybar
sxhkd -c ~/.config/sxhkd/wm_bindings &
sxhkd -c ~/.config/sxhkd/app_bindings &
polybar hd &

get_colours () {
    BG=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
    NORMAL=$(xrdb -query | grep 'color10:'| awk '{print $NF}')
    FOCUSED=$(xrdb -query | grep 'color8:'| awk '{print $NF}')
}
get_colours

bspc config focused_border_color "$FOCUSED"
bspc config presel_feedback_color "$FOCUSED"
bspc config normal_border_color "$NORMAL"
bspc config active_border_color "$NORMAL"

bspc monitor -d  1 2 3 4 5 6 7 8 9
bspc config border_width         2
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config top_padding 26
# bspc config bottom_padding 0
bspc config window_gap 0

# RULES
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

# hsetroot -solid "$BG"
