---
- name: Bootstrap Server
  hosts: server-1
  become: true
  tags:
    - bootstrap
  roles:
    - role: base
    - role: data

- name: Deploy Services
  hosts: server-1
  become: true
  tags:
    - services
  roles:
    - role: headscale
    - role: caddy
    - role: tailscale
    - role: syncthing

- name: Configure Workstation
  hosts: localhost
  connection: local
  become: false
  gather_facts: true

  tags:
    - workstation
  roles:
    - init
    - nix
    - stow
    - gnupg
    - npm
    - git
    - post
